# Generated by Django 3.0.2 on 2021-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=10)),
                ('testname', models.CharField(max_length=20)),
                ('grade', models.CharField(default='null', max_length=5)),
                ('subject', models.CharField(default='null', max_length=5)),
                ('examinfos', models.CharField(default='null', max_length=3)),
                ('writer', models.CharField(max_length=5)),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='date upload')),
            ],
        ),
        migrations.CreateModel(
            name='Uploaduseranswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=5)),
                ('stu_ID', models.CharField(max_length=7)),
                ('subject', models.CharField(max_length=5)),
                ('result', models.IntegerField()),
                ('wrong', models.CharField(max_length=50)),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='date upload')),
            ],
            options={
                'ordering': ['result'],
            },
        ),
    ]
