# Generated by Django 3.0.2 on 2021-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadanswer',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date upload'),
        ),
        migrations.AlterField(
            model_name='uploaduseranswer',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date upload'),
        ),
    ]
