# Generated by Django 3.0.2 on 2021-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.TextField(default=''),
        ),
    ]
