# Generated by Django 3.2.6 on 2021-09-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userrank',
            field=models.IntegerField(default=0),
        ),
    ]
